### ISSUE TITLE
Update MacOS GitLab CI/CD configuration by 31st May

### ISSUE THREAD

**Issue by CMCDragonkai** [MatrixAI/js-quic#25]
The beta macos machines will be deprecated by 31st May and from then it will be running on the M1 architecture, and will require us to have premium subscription to GitLab again.

See: 

* https://github.com/MatrixAI/js-quic/issues/7#issuecomment-1551451917
* https://gitlab.com/gitlab-com/runner-saas-macos-access-requests/-/issues/233#note_1394334519

Note that if we were to go towards full cross-compilation we may avoid this. But since we have other code like js-db and later that may still use node-gyp we're going to need it anyway.

Do note that M1 and x64 macos is capable of cross compiling architectures. We don't bother with the universal binary cause it's not needed, we are able to publish separate optional packages atm. That way `lipo` is avoided. That does mean though... when distributing PK, we have to distribute an M1 version and a x64 version. The x64 versions are likely to be deprecated in the following years.

### Tasks

- [ ] 1. Use `saas-macos-medium-m1` as the tag.
- [ ] 2. Use `macos-12-xcode-14` as the image.
- [ ] 3. Test that build still works fine on M1

**Comment by CMCDragonkai** [comment]
I've switched over in `js-async-cancellable`. However since we aren't on premium package atm, it's not working. So for now we will just have disable macos jobs while we proceed.

@tegefaulkes beware of this for PK @amydevs 

Just disable the macos jobs for what you're doing atm.

**Comment by CMCDragonkai** [comment]
This is now doable. Everybody must update their repos with this.

**Comment by tegefaulkes** [comment]
Updated for js-quic.

**Comment by CMCDragonkai** [comment]
When updating to the new macos, for the macos jobs to work when benchmarks are used, we need to update to `5.18.5`.

See: https://github.com/MatrixAI/js-db/pull/64#issuecomment-1607397092

So if there are benchmarks and `systeminformation` exists, then we need to add it in.

**Comment by CMCDragonkai** [comment]
I've done this for js-db and released 5.2.0 for now with the latest libraries.

**Comment by CMCDragonkai** [comment]
I'm going to move this issue to Polykey since it's about all libraries.
