### ISSUE TITLE
Graceful connection failure for failed TLS handshake

### ISSUE THREAD

**Issue by tegefaulkes** [MatrixAI/js-quic#9]
### Specification

Currently we are seeing unintended behaviour when the connection fails a TLS handshake. 

What we want to happen is, if a connection fails the TLS handshake then we close the connection.
1. The connection should gracefully end for both the server and client. 
2. any further attempts to establish the connection is ended.
3. Errors are propagated and the failure condition is clearly indicated to the best of our ability. This should mainly state that the TLS failed, hopefully it will specify why the TLS failed.

We need to add tests to test these conditions. The tests should check for 
1. Connection success
2. Server certs fail verification
3. Client certs fail verification
4. Both server and client certs fail verification
5. We should test RSA, EC and ED signed certs.

The main way we can trigger verification failure is to have the certs self signed. We can make the certs succeed verification by providing a CA cert that allows the self signed signature.

### Additional context

* Related https://github.com/MatrixAI/js-quic/issues/8?notification_referrer_id=NT_kwDOAVYv-bM2MTQ0NDg3OTI5OjIyNDI1NTkz#issuecomment-1510657734

### Tasks

1. [x] Expand tests to test for the above conditions
2. [x] Fix up the connection logic to match the expected behaviour.
3. [x] Add text fixtures for certs. These should be included in git.

**Comment by tegefaulkes** [comment]
Still getting my head around the library right now but I think I have a good idea of the problem now.

When the client fails the TLS handshake it starts the `quiche` connection closing proceedure. It enters a draining state where the `send` and `recv` calls need to be flushed. That is, packets need to be processed until the connection is closed. This is required so that the `quic` protocol can exchange the ending frames to gracefully close the connection. 

The underlying problem is in two parts.
1. The `QUICConnection` was trying to destroy itself during the draining state due to some bad logic.
2. The `createQUICClient` factory was trying to stop the underlying socket before the `QUICConnection` had time to drain and clean up. resulting in an error due to the existing connection.

**Comment by CMCDragonkai** [comment]
Beware that the timeout mechanism I had was just a prototype. I didn't fully understand how quiche actually times out an idle connection, so the entire flow might be missing something critical.

**Comment by tegefaulkes** [comment]
The connection is failing gracefully now. I think there may be a problem with it timing out so I need to look into that. 

There is an oddity as well, The client is failing to verify the server due to `CONNECTION_CLOSE (Transport) Error code: CRYPTO_ERROR (Unknown CA)`, `TLS Alert Description: Unknown CA (48)`. This is somewhat expected due to the cert being self signed. But setting the CA doesn't fix this.  Just another thing to look into.

**Comment by CMCDragonkai** [comment]
The standard TLS verification logic should accept a cert if it is trusted and if it put into the CA, it should be trusted.

However there are details relating to how CA verification works and the chain verification procedure.

See this guideline:

https://en.m.wikipedia.org/wiki/Certification_path_validation_algorithm

Exact details is in RFC 5280

**Comment by CMCDragonkai** [comment]
Review https://datatracker.ietf.org/doc/html/rfc5280#section-6

**Comment by CMCDragonkai** [comment]
You can always play around with actually signing certs by a CA cert. There should be a tutorial on how to do this with step-cli. I've done it before with openssl and step-cli and step-ca is lot easier.

**Comment by tegefaulkes** [comment]
Some oddities to address
1. Can't get verifying the server to work, providing the server's cert chain as the CA doesn't seem to allow it.
2. It doesn't matter what certs are provided for the client, trying to verify it always succeeds.
3. Client doesn't fail properly when using the `OKP` signed cert. results in a timeout error and then the test timing out.

**Comment by CMCDragonkai** [comment]
Can you also do a sanity check against quiche's bundled QUIC server/client code?

See README.md, go to the place and do `cargo build --exmaples`. There's a `quiche-client` and `quiche-server`.

Maybe something is wrong with the binding, and quiche actually can handle it.

**Comment by tegefaulkes** [comment]
Using certs that are signed by a local `CA` cert seems to work. tests with `verifyPeer` enabled are working now so long as we provide the `CA`.  

From what I can tell is that trying to use the `tlsConfig` cert as the `CA` cert doesn't work. Using the `CA` cert for the `TLS` and the `CA` cert does not work.

Let me check a few things.

**Comment by tegefaulkes** [comment]
It seems that it doesn't like our `Polykey` generated certs as a CA cert. I'm still looking into why.

```
// Generated polykey cert
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number: 1 (0x1)
    Signature Algorithm: Ed25519
        Issuer: CN=IssuerId
        Validity
            Not Before: Apr 19 06:32:15 2023 UTC
            Not After : Apr 18 06:32:15 2024 UTC
        Subject: CN=SubjectID
        Subject Public Key Info:
            Public Key Algorithm: Ed25519
                Public-Key: (32 bit)
                    74:39:84:a5:79:af:eb:81:a0:0a:1d:45:81:80:ba:
                    30:9b:6e:a4:eb:73:98:61:26:ef:b6:74:ca:ed:17:
                    4d:1a
        X509v3 extensions:
            X509v3 Basic Constraints:
                CA:TRUE
            X509v3 Key Usage:
                Digital Signature, Content Commitment, Key Encipherment, Data Encipherment, Key Agreement, Certificate Sign, CRL Sign
            X509v3 Extended Key Usage:
                Server Authentication, Client Authentication, Code Signing, E-mail Protection, Time Stamping, OCSP Signing
            X509v3 Subject Key Identifier:
                E6:3B:87:ED:B5:7C:E1:2E:DF:5F:26:D1:71:87:55:35:A3:1F:B1:B6
    Signature Algorithm: Ed25519
         48:fa:16:f4:90:bf:e7:59:a0:4f:12:63:ff:5a:99:f5:a0:5f:
         af:d5:fe:8c:a7:21:79:35:ea:25:81:28:e5:6e:3a:1c:31:4a:
         bb:5e:3e:4e:f4:6c:7a:4c:73:39:b9:c8:6d:89:d8:37:f2:fe:
         d4:54:d1:48:5e:d1:5a:00:e5:08

// Step-cli generated CA cert
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number: 141800250074057010007996631794800602776 (0x6aadbc1a24cefc46d73eac50f3ef2e98)
    Signature Algorithm: Ed25519
        Issuer: CN=okpCA
        Validity
            Not Before: Apr 19 05:07:54 2023 UTC
            Not After : Apr 18 05:07:54 2024 UTC
        Subject: CN=okpCA
        Subject Public Key Info:
            Public Key Algorithm: Ed25519
                Public-Key: (32 bit)
                    e9:dc:22:21:c5:04:11:b6:a0:72:cc:db:53:c9:61:
                    0f:68:70:02:6e:b4:23:86:2e:08:ad:f7:2d:f2:8a:
                    d3:9d
        X509v3 extensions:
            X509v3 Key Usage: critical
                Certificate Sign, CRL Sign
            X509v3 Basic Constraints: critical
                CA:TRUE, pathlen:1
            X509v3 Subject Key Identifier:
                61:B8:9C:4A:48:7F:51:93:DB:F8:7C:24:5D:49:81:FB:20:6F:A4:9F
    Signature Algorithm: Ed25519
         03:6e:ee:65:cf:7f:1f:9a:8b:eb:cd:17:ef:9d:5b:32:60:b3:
         38:1e:bf:56:f8:ba:9c:55:dc:86:89:36:d2:d6:36:86:a8:27:
         e5:62:55:a0:1d:7d:2b:43:5a:f8:96:0c:50:69:13:38:bf:e3:
         bc:ce:dc:d6:5d:c2:e9:45:3f:06
```

**Comment by tegefaulkes** [comment]
I need to review the possible errors for a failing connection. Any lower level error needs to be wrapped in a domain level error.

**Comment by tegefaulkes** [comment]
Stopping the `QUICServer` is kind of slow? I'll need to look into that.

**Comment by tegefaulkes** [comment]
Odd, the server connection takes about 3 seconds to end if the handshake fails using an `OKP` cert. 

```
// failure using RSA
1	0.000000000	127.0.0.1	127.0.0.1	QUIC	1242	59513	Initial, DCID=a6b92297c965643a3451baf84736a21b, SCID=2eefeb591ecc4a01a7295a70ca4915d5433d228f, PKN: 0, CRYPTO
2	0.003068262	127.0.0.1	127.0.0.1	QUIC	250	41636	Retry, DCID=2eefeb591ecc4a01a7295a70ca4915d5433d228f, SCID=4b9c23098f7e2eff5bf4a5d4e9f84433bc74a4c2
3	0.003879451	127.0.0.1	127.0.0.1	QUIC	1242	59513	Initial, DCID=4b9c23098f7e2eff5bf4a5d4e9f84433bc74a4c2, SCID=2eefeb591ecc4a01a7295a70ca4915d5433d228f, PKN: 1, CRYPTO
4	0.006423819	127.0.0.1	127.0.0.1	QUIC	1242	41636	Handshake, DCID=2eefeb591ecc4a01a7295a70ca4915d5433d228f, SCID=4b9c23098f7e2eff5bf4a5d4e9f84433bc74a4c2, PKN: 0, CRYPTO
5	0.006530618	127.0.0.1	127.0.0.1	QUIC	412	41636	Handshake, DCID=2eefeb591ecc4a01a7295a70ca4915d5433d228f, SCID=4b9c23098f7e2eff5bf4a5d4e9f84433bc74a4c2, PKN: 1, CRYPTO
6	0.007272409	127.0.0.1	127.0.0.1	QUIC	1242	59513	Handshake, DCID=4b9c23098f7e2eff5bf4a5d4e9f84433bc74a4c2, SCID=2eefeb591ecc4a01a7295a70ca4915d5433d228f, PKN: 0, ACK
7	0.008079798	127.0.0.1	127.0.0.1	QUIC	113	59513	Handshake, DCID=4b9c23098f7e2eff5bf4a5d4e9f84433bc74a4c2, SCID=2eefeb591ecc4a01a7295a70ca4915d5433d228f, PKN: 1, CC
```

```
// Failure using OKP, takes 3 seconds to end
1	0.000000000	127.0.0.1	127.0.0.1	QUIC	1242	33749	Initial, DCID=253891e61c750c82caeb64019b69eb25, SCID=d1caa633f38242a1e03f21da7e17fc9e896903d5, PKN: 0, CRYPTO
2	0.003466857	127.0.0.1	127.0.0.1	QUIC	250	52569	Retry, DCID=d1caa633f38242a1e03f21da7e17fc9e896903d5, SCID=f1283dcb4ef1c8d3182e9ed47b6f2f6e3cbfae21
3	0.004361246	127.0.0.1	127.0.0.1	QUIC	1242	33749	Initial, DCID=f1283dcb4ef1c8d3182e9ed47b6f2f6e3cbfae21, SCID=d1caa633f38242a1e03f21da7e17fc9e896903d5, PKN: 1, CRYPTO
4	0.006490819	127.0.0.1	127.0.0.1	QUIC	1242	52569	Handshake, DCID=d1caa633f38242a1e03f21da7e17fc9e896903d5, SCID=f1283dcb4ef1c8d3182e9ed47b6f2f6e3cbfae21, PKN: 0, CRYPTO
5	0.007719804	127.0.0.1	127.0.0.1	QUIC	1242	33749	Initial, DCID=f1283dcb4ef1c8d3182e9ed47b6f2f6e3cbfae21, SCID=d1caa633f38242a1e03f21da7e17fc9e896903d5, PKN: 2, CC
```

Seems that the client ends the connection sooner when using OKP. This may be affecting the clean up logic.

**Comment by tegefaulkes** [comment]
Looks like there is an underlying logic problem with handling the streams. More specifically, handling streams ending. 

I have a feeling it's related to the `timeout()` and `on_timeout()` handling. 

I think in general I need to review and refactor the event handling for send, recv, close, timeout and on_timeout. Double check they're all called as intended when intended as described by the docs.

**Comment by tegefaulkes** [comment]
General notes about how each event is handled.

#### Recv

This is called when a packet is received. this is how we put the data into quiche. It needs to be called when we receive data. Overall pretty simple

1. Is called when data is received from the socket,

#### Send

This is more complex. It is how we get data out of quiche to send. Send must be called multiple times until the outgoing data is drained. 

Send must be processed after the following events.
1. After we process received data with `recv()`.
2. After a timeout, so when we call `on_timeout()`.
3. After receiving data from the application side to send. so after data from the streams. e.g. `stream_send()` and `stream_shutdown()`.
4. After taking data from the stream. `stream_recv()`.

Important, when `is_draining()` is true, we don't need to send anymore, we're only waiting for received packets.


#### close

Closing is generally handled automatically by quiche. The only times we want to call `close()` is when we want to end the connection or there was some error with the underlying socket.

This doesn't close the connection immediately, so we still need to process `recv()`, `send()`, `timeout()` and `on_timeout()` until the connection is closed with `is_closed()` is true.

#### Timeouts

Timeouts are a misnomer here I think. It's the interface for `quiche` to understand timing and not strictly the connection timing out.

`timeout()` returns the amount of time till the next timeout. If it is null the timer should be disarmed. When the timeout ends we need to call `on_timeout()` to let `quiche` know. We should then start processing `send()`.

**Comment by tegefaulkes** [comment]
Some changes I need to make.
1. Send should be a NOP when connection is draining, there won't be any packets to send anyway.
2. I think clean up should trigger on the `closeP.then`. Destroy should signal close and await this promise. Clean up should happen in the background regardless of `destroy()` being called. OR we always call `destroy` when cleaning up but `destroy` needs to be non-blocking in some cases.
3. Might need a shorter timeout? It's not really the connection timing out I think. But connection closing depends on timing out and calling `on_timeout`. so far as I can tell. That may not be the case, still looking into this. In any case, a connection timeout is indicated by `conn.isTimedOut()`

**Comment by tegefaulkes** [comment]
I'm starting to think this may be a bug with `quiche`. Between the `RSA` case where connections clean up quickly and the `ed25519` case where it takes it's time. The only difference is that the `ed25519` case the timeout asks for an extra 3-ish seconds. 

I can't tell if this is a bug or intentional. I might need to make an upstream issue about this. For now I'm going to consider things functional. I just need to clean up the code a little bit.

Keep in mind. it doesn't take this long to close a connection when the handshake succeeds. It only takes an extra 3 seconds when the handshake fails with a `ed25519` cert.

**Comment by CMCDragonkai** [comment]
Did you check where the delay comes from? Did you use console.time?

21 Apr 2023 12:02:34 Brian Botha ***@***.***>:

**Comment by CMCDragonkai** [comment]
Does the delay affect the logic of the system?

21 Apr 2023 12:02:34 Brian Botha ***@***.***>:

**Comment by tegefaulkes** [comment]
The delay comes from the `conn.timeout()` and `conn.onTimeout()` interaction. `quiche` is deciding to wait 3 seconds before deciding that the connection has closed.

During normal failure, both sides will enter a draining state after the close frame has been sent by the client. They then cycle through the timeouts a few times with 0 time before `isClosed()` becomes true. After that they finish cleaning up.

In the bad case, more or less the same happens, but the server asks for 3-ish seconds during one of the timeout cycles.

**Comment by tegefaulkes** [comment]
Created an upstream issue at https://github.com/cloudflare/quiche/issues/1488.

**Comment by tegefaulkes** [comment]
I'll make a new issue about the weird connection timeout problem. Besides that, I think all that is left here is...
1. Work out why client verification succeeds regardless of it's tlsConfig, provided CA or value of server's `verifyPeer`. Maybe setting or verifying the cert is handled differently in this case? I should check what cert the client is ultimately sending.
2. Fill in some todo tests for certain connection failure conditions. socket fails and throws error, connection establishes but socket stops responding, etc etc.

**Comment by tegefaulkes** [comment]
The client is not even sending a cert chain?. At least, the server connection `serverConn.conn.peerCertChain()` is returning null. This is very odd. If we're verifying the peer, wouldn't verification fail if no cert was provided?

**Comment by tegefaulkes** [comment]
I need to fix this in two parts.
1. Make sure that client verification fails when client doesn't provide a cert. I think that this can only be done with the boring context.
2. Make sure that the client actually sends the certs. We are giving it a cert but why is it not sending it?

**Comment by CMCDragonkai** [comment]
Indeed that is pretty strange, though by default the server doesn't verify the client chain.

BTW, do note it is possible that there's a separate settings for setting the client certificate.

**Comment by tegefaulkes** [comment]
I've noticed something. It looks like the connection can establish before a handshake has finished. This means the client will be created and resolved before certs are checked. This may be causing problems generally. I can create a promise for the handshake completion and check that.

One question is, by design do we want the client and connection to be created and resolve before or after the handshake? That is, do we want to wait for the handshake result before fully creating the client?

**Comment by CMCDragonkai** [comment]
So connection setup goes through 2 stages:

1. QUIC packet bootstrapping - this is synchronising the SCID and DCID, this does not involve TLS at all
2. TLS handshake, this is done in the quiche library itself

When `QUICClient` is creating, it waits until stage 2 is complete.

But `QUICConnection` exists without stage 1 completing. This is because a `QUICConnection` has to exist, in order to start the handling of stage 1 and stage 2.

**Comment by tegefaulkes** [comment]
Wait, after reviewing the docs `is_established()` becomes true after the handshake. Maybe I misinterpreted the docs. Let me review the logs again.

**Comment by tegefaulkes** [comment]
Ok this is weird. I can see the server failing the client's TLS, but this is happening AFTER the client has established the connection. According to the docs, establishment happens after the handshake completes. So how can the server fail TLS verification AFTER the connection has established?

Are the docs just vague and connection handshake and TLS handshake are separate?

**Comment by CMCDragonkai** [comment]
Not sure about what the docs is saying, but from the packet logs, it is clear what the 2 stages are.

Connection establishment could mean many things. From the perspective of `QUICConnection` it should be after both stages are ready.

However there is an early startup option, that might change the behaviour a bit.

**Comment by tegefaulkes** [comment]
After digging through the RFC, I think this is a bug with `quiche`. 

1. https://docs.rs/quiche/latest/quiche/struct.Connection.html#method.is_established States that `is_established()` becomes true once the handshake has completed.
2. RFC9000 states that the Handshake is only considered complete once the both the server has been authenticated and the client has optionally been authenticated. And the `HANDSHAKE_DONE` frame has been sent and ACKed.
3. TLS allows for post-handshake authentication but QUIC explicitly states that this should not be used. https://datatracker.ietf.org/doc/html/rfc9001#name-peer-authentication. I don't think this is what's happening.

Here are the packet logs for the test.
```
1	0.000000000	127.0.0.1	127.0.0.1	34238	QUIC	1242	Initial, DCID=494077f00d584ca236388136a42f9a6d, SCID=fa93ec24c633d1f91662cb586d0b57c46cca0dec, PKN: 0, CRYPTO
2	0.002128503	127.0.0.1	127.0.0.1	34148	QUIC	250	Retry, DCID=fa93ec24c633d1f91662cb586d0b57c46cca0dec, SCID=4adf076468fb432462e51fb1018c79749b21e0dc
3	0.003273495	127.0.0.1	127.0.0.1	34238	QUIC	1242	Initial, DCID=4adf076468fb432462e51fb1018c79749b21e0dc, SCID=fa93ec24c633d1f91662cb586d0b57c46cca0dec, PKN: 1, CRYPTO
4	0.006133042	127.0.0.1	127.0.0.1	34148	QUIC	1242	Handshake, DCID=fa93ec24c633d1f91662cb586d0b57c46cca0dec, SCID=4adf076468fb432462e51fb1018c79749b21e0dc, PKN: 0, CRYPTO
// Client enters established state here.
5	0.039734489	127.0.0.1	127.0.0.1	34238	QUIC	1242	Handshake, DCID=4adf076468fb432462e51fb1018c79749b21e0dc, SCID=fa93ec24c633d1f91662cb586d0b57c46cca0dec, PKN: 0, ACK, CRYPTO
6	0.040731996	127.0.0.1	127.0.0.1	34238	QUIC	162	Handshake, DCID=4adf076468fb432462e51fb1018c79749b21e0dc, SCID=fa93ec24c633d1f91662cb586d0b57c46cca0dec, PKN: 1, ACK, CRYPTO
// Server rejects client's TLS cert here
7	0.067375517	127.0.0.1	127.0.0.1	34148	QUIC	113	Handshake, DCID=fa93ec24c633d1f91662cb586d0b57c46cca0dec, SCID=4adf076468fb432462e51fb1018c79749b21e0dc, PKN: 1, CC
8	0.071265881	127.0.0.1	127.0.0.1	34238	QUIC	162	Handshake, DCID=4adf076468fb432462e51fb1018c79749b21e0dc, SCID=fa93ec24c633d1f91662cb586d0b57c46cca0dec, PKN: 2, ACK, CRYPTO
9	0.071536492	127.0.0.1	127.0.0.1	34238	QUIC	115	Handshake, DCID=4adf076468fb432462e51fb1018c79749b21e0dc, SCID=fa93ec24c633d1f91662cb586d0b57c46cca0dec, PKN: 3, ACK, PING
```

The only conclusion I can make here is that the client connection is wrongfully returning `is_established() -> true` far too early. As you can see, a `HANDSHAKE_DONE` frame is never sent. 

For reference, normal establishment looks like this.

```
1	0.000000000	127.0.0.1	127.0.0.1	36275	QUIC	1242	Initial, DCID=299582cc5ab22a21e56e76591e28b1bd, SCID=c577439e01a0dcb123b5005c790f1959cdc65459, PKN: 0, CRYPTO
2	0.002151087	127.0.0.1	127.0.0.1	43749	QUIC	250	Retry, DCID=c577439e01a0dcb123b5005c790f1959cdc65459, SCID=b5e03103516e73f4506ee5565710db8455111925
3	0.003300591	127.0.0.1	127.0.0.1	36275	QUIC	1242	Initial, DCID=b5e03103516e73f4506ee5565710db8455111925, SCID=c577439e01a0dcb123b5005c790f1959cdc65459, PKN: 1, CRYPTO
4	0.006159623	127.0.0.1	127.0.0.1	43749	QUIC	1242	Handshake, DCID=c577439e01a0dcb123b5005c790f1959cdc65459, SCID=b5e03103516e73f4506ee5565710db8455111925, PKN: 0, CRYPTO
// client establishes here
5	0.043200211	127.0.0.1	127.0.0.1	36275	QUIC	1242	Handshake, DCID=b5e03103516e73f4506ee5565710db8455111925, SCID=c577439e01a0dcb123b5005c790f1959cdc65459, PKN: 0, ACK, CRYPTO
6	0.044810146	127.0.0.1	127.0.0.1	36275	QUIC	154	Handshake, DCID=b5e03103516e73f4506ee5565710db8455111925, SCID=c577439e01a0dcb123b5005c790f1959cdc65459, PKN: 1, ACK, CRYPTO
// Server establishes here
7	0.046969036	127.0.0.1	127.0.0.1	43749	QUIC	529	Protected Payload (KP0), DCID=c577439e01a0dcb123b5005c790f1959cdc65459, PKN: 0, DONE, CRYPTO
8	0.050229052	127.0.0.1	127.0.0.1	36275	QUIC	86	Protected Payload (KP0), DCID=b5e03103516e73f4506ee5565710db8455111925, PKN: 0, ACK
```

 This also seems to have the client entering the established state early. We can see the `HANDSHAKE_DONE` frame as `DONE` in packet 7. Based on my interpretation of the docs, the client should be established after receiving packet 7, and the server after packet 8.

I'll probably have to make an upstream issue for this.

**Comment by tegefaulkes** [comment]
Upstream issue created at https://github.com/cloudflare/quiche/issues/1489.

**Comment by tegefaulkes** [comment]
I just double checked, setting `verifyPeer: true` via the `quiche` config will not fail the `TLS` if no client certificate was provided. So we do have to set it via the `boring::SslContext`.

**Comment by tegefaulkes** [comment]
While the client not failing creation due to the client certificate failing is annoying, it's not critical. The connection will error out due to a TLS failure soon after establishment. AS such, the problem is not critical for moving forward. I'll make an issue for tracking the problem, but otherwise we can more on from it.

**Comment by tegefaulkes** [comment]
New issue created at #12

**Comment by tegefaulkes** [comment]
Ah so we ARE receiving the client certificate, it's just after the connection has 'established' due to the aforementioned bug.
I can create a `peerCert` promise to resolve with the cert. Might not be super useful, by default we don't send a client cert so on the server side that promise may never resolve. Client side always receives the cert.

Timing wise, I think the certs are available the moment the frame containing them is processed.

**Comment by tegefaulkes** [comment]
example packet logs

<details>

#### Server authenticates

```
1	0.000000000	127.0.0.1	127.0.0.1	43777	QUIC	1242	Initial, DCID=5c4e1121b7e0463b7cb825c3b46238ff, SCID=98f94c64ca56545ff50f8764934d1e3d34840770, PKN: 0, CRYPTO
2	0.003712710	127.0.0.1	127.0.0.1	51090	QUIC	250	Retry, DCID=98f94c64ca56545ff50f8764934d1e3d34840770, SCID=d9ae3a45971cd31b1136b7e8727846844120d094
3	0.004854716	127.0.0.1	127.0.0.1	43777	QUIC	1242	Initial, DCID=d9ae3a45971cd31b1136b7e8727846844120d094, SCID=98f94c64ca56545ff50f8764934d1e3d34840770, PKN: 1, CRYPTO
4	0.007844097	127.0.0.1	127.0.0.1	51090	QUIC	1242	Handshake, DCID=98f94c64ca56545ff50f8764934d1e3d34840770, SCID=d9ae3a45971cd31b1136b7e8727846844120d094, PKN: 0, CRYPTO
5	0.009925021	127.0.0.1	127.0.0.1	43777	QUIC	1242	Handshake, DCID=d9ae3a45971cd31b1136b7e8727846844120d094, SCID=98f94c64ca56545ff50f8764934d1e3d34840770, PKN: 0, ACK, CRYPTO
6	0.010997496	127.0.0.1	127.0.0.1	51090	QUIC	529	Protected Payload (KP0), DCID=98f94c64ca56545ff50f8764934d1e3d34840770, PKN: 0, DONE, CRYPTO
7	0.012072258	127.0.0.1	127.0.0.1	43777	QUIC	85	Protected Payload (KP0), DCID=d9ae3a45971cd31b1136b7e8727846844120d094, PKN: 0, ACK
8	2.013562871	127.0.0.1	127.0.0.1	43777	QUIC	84	Protected Payload (KP0), DCID=d9ae3a45971cd31b1136b7e8727846844120d094, PKN: 1, CC
```

#### Client authenticates

```
1	0.000000000	127.0.0.1	127.0.0.1	33159	QUIC	1242	Initial, DCID=bc038d00a856bbd2deac451c28b7642f, SCID=b67eef3f56aa6bb33f1641d3ad2186544c80c97d, PKN: 0, CRYPTO
2	0.003743760	127.0.0.1	127.0.0.1	39747	QUIC	250	Retry, DCID=b67eef3f56aa6bb33f1641d3ad2186544c80c97d, SCID=ec3a8045de274f1ffb0232d77aad37e818af6806
3	0.005005743	127.0.0.1	127.0.0.1	33159	QUIC	1242	Initial, DCID=ec3a8045de274f1ffb0232d77aad37e818af6806, SCID=b67eef3f56aa6bb33f1641d3ad2186544c80c97d, PKN: 1, CRYPTO
4	0.007996257	127.0.0.1	127.0.0.1	39747	QUIC	1242	Handshake, DCID=b67eef3f56aa6bb33f1641d3ad2186544c80c97d, SCID=ec3a8045de274f1ffb0232d77aad37e818af6806, PKN: 0, CRYPTO
5	0.010223545	127.0.0.1	127.0.0.1	33159	QUIC	1242	Handshake, DCID=ec3a8045de274f1ffb0232d77aad37e818af6806, SCID=b67eef3f56aa6bb33f1641d3ad2186544c80c97d, PKN: 0, ACK, CRYPTO
6	0.011320861	127.0.0.1	127.0.0.1	39747	QUIC	1265	Protected Payload (KP0), DCID=b67eef3f56aa6bb33f1641d3ad2186544c80c97d, PKN: 0, DONE, CRYPTO
7	0.012516271	127.0.0.1	127.0.0.1	33159	QUIC	85	Protected Payload (KP0), DCID=ec3a8045de274f1ffb0232d77aad37e818af6806, PKN: 0, ACK
8	2.013143760	127.0.0.1	127.0.0.1	33159	QUIC	84	Protected Payload (KP0), DCID=ec3a8045de274f1ffb0232d77aad37e818af6806, PKN: 1, CC
```

#### Both succeed

```
1	0.000000000	127.0.0.1	127.0.0.1	46251	QUIC	1242	Initial, DCID=86e1cf0cfd9c2ee47da1e2bdb8042cc6, SCID=49d031267f90cd01dd9945c33bd57c0ec295edd3, PKN: 0, CRYPTO
2	0.003642051	127.0.0.1	127.0.0.1	53021	QUIC	250	Retry, DCID=49d031267f90cd01dd9945c33bd57c0ec295edd3, SCID=b288738a0806cdf651c00020cea8c186c32c4f7b
3	0.004839655	127.0.0.1	127.0.0.1	46251	QUIC	1242	Initial, DCID=b288738a0806cdf651c00020cea8c186c32c4f7b, SCID=49d031267f90cd01dd9945c33bd57c0ec295edd3, PKN: 1, CRYPTO
4	0.007648113	127.0.0.1	127.0.0.1	53021	QUIC	1242	Handshake, DCID=49d031267f90cd01dd9945c33bd57c0ec295edd3, SCID=b288738a0806cdf651c00020cea8c186c32c4f7b, PKN: 0, CRYPTO
5	0.009807038	127.0.0.1	127.0.0.1	46251	QUIC	1242	Handshake, DCID=b288738a0806cdf651c00020cea8c186c32c4f7b, SCID=49d031267f90cd01dd9945c33bd57c0ec295edd3, PKN: 0, ACK, CRYPTO
6	0.010900531	127.0.0.1	127.0.0.1	53021	QUIC	1265	Protected Payload (KP0), DCID=49d031267f90cd01dd9945c33bd57c0ec295edd3, PKN: 0, DONE, CRYPTO
7	0.012040109	127.0.0.1	127.0.0.1	46251	QUIC	85	Protected Payload (KP0), DCID=b288738a0806cdf651c00020cea8c186c32c4f7b, PKN: 0, ACK
8	2.013866149	127.0.0.1	127.0.0.1	46251	QUIC	84	Protected Payload (KP0), DCID=b288738a0806cdf651c00020cea8c186c32c4f7b, PKN: 1, CC
```

#### Server fails TLS

```
1	0.000000000	127.0.0.1	127.0.0.1	35386	QUIC	1242	Initial, DCID=288a0555c31e81f68ace9bcfe716a475, SCID=b9403ae9a9935bceb286e47c606974ea70d9faf8, PKN: 0, CRYPTO
2	0.003781434	127.0.0.1	127.0.0.1	48578	QUIC	250	Retry, DCID=b9403ae9a9935bceb286e47c606974ea70d9faf8, SCID=2d905692ed6e9ffe25ca3b4a05d5f50f66054b1f
3	0.005181244	127.0.0.1	127.0.0.1	35386	QUIC	1242	Initial, DCID=2d905692ed6e9ffe25ca3b4a05d5f50f66054b1f, SCID=b9403ae9a9935bceb286e47c606974ea70d9faf8, PKN: 1, CRYPTO
4	0.008470895	127.0.0.1	127.0.0.1	48578	QUIC	1242	Handshake, DCID=b9403ae9a9935bceb286e47c606974ea70d9faf8, SCID=2d905692ed6e9ffe25ca3b4a05d5f50f66054b1f, PKN: 0, CRYPTO
5	0.072273683	127.0.0.1	127.0.0.1	35386	QUIC	1242	Initial, DCID=2d905692ed6e9ffe25ca3b4a05d5f50f66054b1f, SCID=b9403ae9a9935bceb286e47c606974ea70d9faf8, PKN: 2, CC
```

#### Client fails TLS

```
1	0.000000000	127.0.0.1	127.0.0.1	43613	QUIC	1242	Initial, DCID=14f1edd18f184bd45eef8706194bdeee, SCID=0d2efac2a8f13537293b3c287ba350df125398d6, PKN: 0, CRYPTO
2	0.003729817	127.0.0.1	127.0.0.1	57027	QUIC	250	Retry, DCID=0d2efac2a8f13537293b3c287ba350df125398d6, SCID=e2de01152dd4163e93937984346849ff9c44286f
3	0.004878576	127.0.0.1	127.0.0.1	43613	QUIC	1242	Initial, DCID=e2de01152dd4163e93937984346849ff9c44286f, SCID=0d2efac2a8f13537293b3c287ba350df125398d6, PKN: 1, CRYPTO
4	0.008069057	127.0.0.1	127.0.0.1	57027	QUIC	1242	Handshake, DCID=0d2efac2a8f13537293b3c287ba350df125398d6, SCID=e2de01152dd4163e93937984346849ff9c44286f, PKN: 0, CRYPTO
5	0.068587075	127.0.0.1	127.0.0.1	43613	QUIC	1242	Handshake, DCID=e2de01152dd4163e93937984346849ff9c44286f, SCID=0d2efac2a8f13537293b3c287ba350df125398d6, PKN: 0, ACK, CRYPTO
6	0.076402952	127.0.0.1	127.0.0.1	43613	QUIC	581	Handshake, DCID=e2de01152dd4163e93937984346849ff9c44286f, SCID=0d2efac2a8f13537293b3c287ba350df125398d6, PKN: 1, ACK, CRYPTO
7	0.107512091	127.0.0.1	127.0.0.1	57027	QUIC	113	Handshake, DCID=0d2efac2a8f13537293b3c287ba350df125398d6, SCID=e2de01152dd4163e93937984346849ff9c44286f, PKN: 1, CC
8	0.108881597	127.0.0.1	127.0.0.1	43613	QUIC	581	Handshake, DCID=e2de01152dd4163e93937984346849ff9c44286f, SCID=0d2efac2a8f13537293b3c287ba350df125398d6, PKN: 2, ACK, CRYPTO
9	0.109154241	127.0.0.1	127.0.0.1	43613	QUIC	115	Handshake, DCID=e2de01152dd4163e93937984346849ff9c44286f, SCID=0d2efac2a8f13537293b3c287ba350df125398d6, PKN: 3, ACK, PING
```

#### Both fail TLS

```
1	0.000000000	127.0.0.1	127.0.0.1	47382	QUIC	1242	Initial, DCID=6a02b909e5208f2d8d80e05b1752e843, SCID=91b46b709b05ca483a2b24dfa431a89bfa650481, PKN: 0, CRYPTO
2	0.004604426	127.0.0.1	127.0.0.1	44551	QUIC	250	Retry, DCID=91b46b709b05ca483a2b24dfa431a89bfa650481, SCID=d4c44ca38da26213204b54ed7ccb50253a11bf2e
3	0.006025339	127.0.0.1	127.0.0.1	47382	QUIC	1242	Initial, DCID=d4c44ca38da26213204b54ed7ccb50253a11bf2e, SCID=91b46b709b05ca483a2b24dfa431a89bfa650481, PKN: 1, CRYPTO
4	0.009326331	127.0.0.1	127.0.0.1	44551	QUIC	1242	Handshake, DCID=91b46b709b05ca483a2b24dfa431a89bfa650481, SCID=d4c44ca38da26213204b54ed7ccb50253a11bf2e, PKN: 0, CRYPTO
5	0.069720954	127.0.0.1	127.0.0.1	47382	QUIC	1242	Initial, DCID=d4c44ca38da26213204b54ed7ccb50253a11bf2e, SCID=91b46b709b05ca483a2b24dfa431a89bfa650481, PKN: 2, CC
```

</details>

**Comment by CMCDragonkai** [comment]
Can you explain what the intended behaviour for each of the 6 situation is?
